/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import GestioneTabella.MyDefaultTableModel;
import GestioneTabella.MyTableCellRenderer;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author giuli
 */
public class ManagementTurnView extends javax.swing.JPanel {

    /**
     * Creates new form MenagementEvents
     */
    MyDefaultTableModel tab;
    
    public ManagementTurnView() {
        initComponents();
        jScrollPane1.getViewport().setOpaque(false);
        buttonCreate.setActionCommand("CREATE");
        buttonDelete.setActionCommand("DELETE");
        buttonSearch.setActionCommand("SEARCH");
        tableMenagementEvents.setDefaultRenderer(Object.class,new MyTableCellRenderer());
        buttonDelete.setEnabled(false);
    }

    public JButton getButtonCreate() {
        return buttonCreate;
    }

    public void setButtonCreate(JButton buttonCreate) {
        this.buttonCreate = buttonCreate;
    }

    public JButton getButtonDelete() {
        return buttonDelete;
    }

    public void setButtonDelete(JButton buttonDelete) {
        this.buttonDelete = buttonDelete;
    }

    public JButton getButtonSearch() {
        return buttonSearch;
    }

    public void setButtonSearch(JButton buttonSearch) {
        this.buttonSearch = buttonSearch;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTableMenagementEvents() {
        return tableMenagementEvents;
    }

    public void setTableMenagementEvents(JTable tableMenagementEvents) {
        this.tableMenagementEvents = tableMenagementEvents;
    }

    public JTextField getTextCodeEvent() {
        return textCodeEvent;
    }

    public void setTextCodeEvent(JTextField textCodeEvent) {
        this.textCodeEvent = textCodeEvent;
    }

    public JTextField getTextTaxCode() {
        return textTaxCode;
    }

    public void setTextTaxCode(JTextField textTaxCode) {
        this.textTaxCode = textTaxCode;
    }

    public void updateTable(Set obj)
    {
         tab = new MyDefaultTableModel();
         tab.createModelBySetTurn((Set) obj);//da aggiungere nuovo metodo dentro a my default tabe model che carica questi.
         
         tableMenagementEvents.setModel(tab);
         int id = tableMenagementEvents.getColumnModel().getColumnIndex("TURN_NUMBER");
         tab.setId_column(id);
         tableMenagementEvents.setRowSorter(new TableRowSorter (tab));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMenagementEvents = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonDelete = new javax.swing.JButton();
        buttonCreate = new javax.swing.JButton();
        buttonSearch = new javax.swing.JButton();
        textCodeEvent = new javax.swing.JTextField();
        textTaxCode = new javax.swing.JTextField();
        sfondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(590, 600));
        setMinimumSize(new java.awt.Dimension(590, 600));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(590, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 600));

        tableMenagementEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "SURNAME", "TITLE", "DATE", "START_TURN", "END_TURN", "TURN_NUMBER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMenagementEvents.setOpaque(false);
        jScrollPane1.setViewportView(tableMenagementEvents);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 710, 450));

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CODE EVENT");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 130, 20));

        jLabel6.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TAX CODE SECURITY");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 20));

        buttonDelete.setBackground(new java.awt.Color(255, 222, 177));
        buttonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/delete.png"))); // NOI18N
        add(buttonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 50, 40));

        buttonCreate.setBackground(new java.awt.Color(255, 222, 177));
        buttonCreate.setFont(new java.awt.Font("Dubai Medium", 1, 8)); // NOI18N
        buttonCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/toWork.png"))); // NOI18N
        buttonCreate.setText("SET WORK");
        add(buttonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 110, 40));

        buttonSearch.setBackground(new java.awt.Color(255, 222, 177));
        buttonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/okButton.png"))); // NOI18N
        add(buttonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 40, 40));
        add(textCodeEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 130, 30));
        add(textTaxCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 130, 30));

        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/pastello.jpg"))); // NOI18N
        sfondo.setOpaque(true);
        add(sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 690));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreate;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sfondo;
    private javax.swing.JTable tableMenagementEvents;
    private javax.swing.JTextField textCodeEvent;
    private javax.swing.JTextField textTaxCode;
    // End of variables declaration//GEN-END:variables
}
