/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import GestioneTabella.MyDefaultTableModel;
import GestioneTabella.MyTableCellRenderer;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author giuli
 */
public class ManagementTurnView extends javax.swing.JPanel {

    /**
     * Creates new form MenagementEvents
     */
    MyDefaultTableModel tab;
    
    public ManagementTurnView() {
        initComponents();
        jScrollPane1.getViewport().setOpaque(false);
        buttonCreateWork.setActionCommand("CREATE");
        buttonDeleteWork.setActionCommand("DELETE");
        buttonSearchWork.setActionCommand("SEARCH");
        tableMenagementEvents.setDefaultRenderer(Object.class,new MyTableCellRenderer());
        buttonDeleteWork.setEnabled(false);
    }

    public JButton getButtonCreate() {
        return buttonCreateWork;
    }

    public void setButtonCreate(JButton buttonCreate) {
        this.buttonCreateWork = buttonCreate;
    }

    public JButton getButtonDelete() {
        return buttonDeleteWork;
    }

    public void setButtonDelete(JButton buttonDelete) {
        this.buttonDeleteWork = buttonDelete;
    }

    public JSpinner getSpinnerEnd() {
        return spinnerEnd;
    }

    public void setSpinnerEnd(JSpinner spinnerEnd) {
        this.spinnerEnd = spinnerEnd;
    }

    public JSpinner getSpinnerStart() {
        return spinnerStart;
    }

    public void setSpinnerStart(JSpinner spinnerStart) {
        this.spinnerStart = spinnerStart;
    }

    public JButton getButtonSearch() {
        return buttonSearchWork;
    }

    public void setButtonSearch(JButton buttonSearch) {
        this.buttonSearchWork = buttonSearch;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTableMenagementEvents() {
        return tableMenagementEvents;
    }

    public void setTableMenagementEvents(JTable tableMenagementEvents) {
        this.tableMenagementEvents = tableMenagementEvents;
    }

    public JTextField getTextCodeEvent() {
        return textCodeEvent;
    }

    public void setTextCodeEvent(JTextField textCodeEvent) {
        this.textCodeEvent = textCodeEvent;
    }

    public JTextField getTextTaxCode() {
        return textTaxCode;
    }

    public void setTextTaxCode(JTextField textTaxCode) {
        this.textTaxCode = textTaxCode;
    }

    public void updateTable(Set obj)
    {
         tab = new MyDefaultTableModel();
         tab.createModelBySetTurn((Set) obj);//da aggiungere nuovo metodo dentro a my default tabe model che carica questi.
         
         tableMenagementEvents.setModel(tab);
         int id = tableMenagementEvents.getColumnModel().getColumnIndex("TURN_NUMBER");
         tab.setId_column(id);
         tableMenagementEvents.setRowSorter(new TableRowSorter (tab));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMenagementEvents = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buttonDeleteWork = new javax.swing.JButton();
        buttonCreateWork = new javax.swing.JButton();
        buttonSearchWork = new javax.swing.JButton();
        textCodeEvent = new javax.swing.JTextField();
        textTaxCode = new javax.swing.JTextField();
        spinnerStart = new javax.swing.JSpinner();
        spinnerEnd = new javax.swing.JSpinner();
        sfondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(590, 600));
        setMinimumSize(new java.awt.Dimension(590, 600));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(590, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 600));

        tableMenagementEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "SURNAME", "TITLE", "DATE", "START_TURN", "END_TURN", "TURN_NUMBER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMenagementEvents.setOpaque(false);
        jScrollPane1.setViewportView(tableMenagementEvents);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 710, 450));

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CODE EVENT");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 130, 20));

        jLabel6.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FROM HOUR");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 80, 20));

        jLabel7.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TO HOUR");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 80, 20));

        jLabel8.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TAX CODE SECURITY");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 130, 20));

        buttonDeleteWork.setBackground(new java.awt.Color(255, 222, 177));
        buttonDeleteWork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/delete.png"))); // NOI18N
        add(buttonDeleteWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 40, 30));

        buttonCreateWork.setBackground(new java.awt.Color(255, 222, 177));
        buttonCreateWork.setFont(new java.awt.Font("Dubai Medium", 1, 8)); // NOI18N
        buttonCreateWork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/toWork.png"))); // NOI18N
        buttonCreateWork.setText("SET WORK");
        add(buttonCreateWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 110, 30));

        buttonSearchWork.setBackground(new java.awt.Color(255, 222, 177));
        buttonSearchWork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/okButton.png"))); // NOI18N
        buttonSearchWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchWorkActionPerformed(evt);
            }
        });
        add(buttonSearchWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 40, 30));
        add(textCodeEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 130, 30));
        add(textTaxCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 130, 30));

        spinnerStart.setModel(new javax.swing.SpinnerNumberModel(1, 1, 24, 1));
        add(spinnerStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 80, 30));

        spinnerEnd.setModel(new javax.swing.SpinnerNumberModel(1, 1, 24, 1));
        add(spinnerEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 80, 30));

        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/pastello.jpg"))); // NOI18N
        sfondo.setOpaque(true);
        add(sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSearchWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSearchWorkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreateWork;
    private javax.swing.JButton buttonDeleteWork;
    private javax.swing.JButton buttonSearchWork;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sfondo;
    private javax.swing.JSpinner spinnerEnd;
    private javax.swing.JSpinner spinnerStart;
    private javax.swing.JTable tableMenagementEvents;
    private javax.swing.JTextField textCodeEvent;
    private javax.swing.JTextField textTaxCode;
    // End of variables declaration//GEN-END:variables
}
