/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author giuli
 */
public class MenagementSecurity extends javax.swing.JPanel {

    /**
     * Creates new form MenagementSecurity
     */
    public MenagementSecurity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMenagementSecurity = new javax.swing.JTable();
        panelMenagementSecurity = new javax.swing.JPanel();
        comboActionMenagementSecurity = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboAdminMenagementSecurity = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        dateMenagementSecurity = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelMenagementWork = new javax.swing.JPanel();
        comboEventsWork = new javax.swing.JComboBox<>();
        comboSecurityWork = new javax.swing.JComboBox<>();
        buttonAddSecurityWork = new javax.swing.JButton();
        buttonBackWork = new javax.swing.JButton();
        sfondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableMenagementSecurity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Action", "Security Officer", "Admin", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableMenagementSecurity);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, 590, 370));

        panelMenagementSecurity.setOpaque(false);
        panelMenagementSecurity.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenagementSecurity.add(comboActionMenagementSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 30));

        jLabel4.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ACTION");
        panelMenagementSecurity.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 20));

        panelMenagementSecurity.add(comboAdminMenagementSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 30));

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMIN");
        panelMenagementSecurity.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 20));
        panelMenagementSecurity.add(dateMenagementSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 140, 30));

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DATE");
        panelMenagementSecurity.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 130, 20));

        jButton1.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jButton1.setText("MENAGEMENT WORK");
        panelMenagementSecurity.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, 50));

        add(panelMenagementSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 100));

        panelMenagementWork.setOpaque(false);
        panelMenagementWork.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboEventsWork.setFont(new java.awt.Font("Dubai Medium", 1, 10)); // NOI18N
        comboEventsWork.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Event" }));
        panelMenagementWork.add(comboEventsWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 150, 30));

        comboSecurityWork.setFont(new java.awt.Font("Dubai Medium", 1, 10)); // NOI18N
        comboSecurityWork.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Security Officer" }));
        panelMenagementWork.add(comboSecurityWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 30));

        buttonAddSecurityWork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/toWork.png"))); // NOI18N
        panelMenagementWork.add(buttonAddSecurityWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 60, 50));

        buttonBackWork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/backIcon.png"))); // NOI18N
        panelMenagementWork.add(buttonBackWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 30, 50, 40));

        add(panelMenagementWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 100));

        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/pastello.jpg"))); // NOI18N
        add(sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 490));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddSecurityWork;
    private javax.swing.JButton buttonBackWork;
    private javax.swing.JComboBox<String> comboActionMenagementSecurity;
    private javax.swing.JComboBox<String> comboAdminMenagementSecurity;
    private javax.swing.JComboBox<String> comboEventsWork;
    private javax.swing.JComboBox<String> comboSecurityWork;
    private com.toedter.calendar.JDateChooser dateMenagementSecurity;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelMenagementSecurity;
    private javax.swing.JPanel panelMenagementWork;
    private javax.swing.JLabel sfondo;
    private javax.swing.JTable tableMenagementSecurity;
    // End of variables declaration//GEN-END:variables
}
