/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author giuli
 */
public class MenagementCustomers extends javax.swing.JPanel {

    /**
     * Creates new form MenagementCustomers
     */
    public MenagementCustomers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMenagementCustomers = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        comboActionMenagementCustomers = new javax.swing.JComboBox<>();
        dateMenagementCustomers = new com.toedter.calendar.JDateChooser();
        comboAdminMenagementCustomers = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        sfondo = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(590, 600));
        setPreferredSize(new java.awt.Dimension(590, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ACTION");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 130, 20));

        tableMenagementCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Action", "Customers", "Admin", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableMenagementCustomers);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, 590, 390));

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMIN");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 130, 20));

        comboActionMenagementCustomers.setBackground(new java.awt.Color(255, 222, 177));
        add(comboActionMenagementCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 130, 30));
        add(dateMenagementCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 140, 30));

        comboAdminMenagementCustomers.setBackground(new java.awt.Color(255, 222, 177));
        add(comboAdminMenagementCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 130, 30));

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DATE");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 130, 20));

        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/pastello.jpg"))); // NOI18N
        add(sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 510));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboActionMenagementCustomers;
    private javax.swing.JComboBox<String> comboAdminMenagementCustomers;
    private com.toedter.calendar.JDateChooser dateMenagementCustomers;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sfondo;
    private javax.swing.JTable tableMenagementCustomers;
    // End of variables declaration//GEN-END:variables
}
