/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author giuli
 */
public class Participation_View extends javax.swing.JPanel {

    /**
     * Creates new form MenagementEvents
     */
    public Participation_View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMenagementEvents = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        dateMenagementEvents = new com.toedter.calendar.JDateChooser();
        sfondo = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(590, 600));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(590, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableMenagementEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Surname", "Title Event", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableMenagementEvents);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, 590, 400));

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TITLE EVENT");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 130, 20));

        jLabel5.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DATE");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 130, 20));

        jLabel6.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TAX CODE");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 20));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 130, 30));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 130, 30));
        add(dateMenagementEvents, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 140, 30));

        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/pastello.jpg"))); // NOI18N
        sfondo.setOpaque(true);
        add(sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 490));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateMenagementEvents;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel sfondo;
    private javax.swing.JTable tableMenagementEvents;
    // End of variables declaration//GEN-END:variables
}
